# -*- coding: utf-8 -*-
"""Food_autoencoder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163iR7NFCDwvIzoxhVkakCXbnrXeoD4eR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/UK_foods.csv',index_col='Unnamed: 0')

df

df.transpose()

plt.figure(figsize=(10,8))
sns.heatmap(df)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

encoder = Sequential()
encoder.add(Dense(units=8,activation='relu',input_shape=[17]))
encoder.add(Dense(units=4,activation='relu',input_shape=[8]))
encoder.add(Dense(units=2,activation='relu',input_shape=[4]))

decoder = Sequential()
decoder.add(Dense(units=4,activation='relu',input_shape=[2]))
decoder.add(Dense(units=8,activation='relu',input_shape=[4]))
decoder.add(Dense(units=17,activation='relu',input_shape=[8]))

autoencoder = Sequential([encoder,decoder])

autoencoder.compile(loss="mse" ,optimizer=SGD(lr=1.5))

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_df = scaler.fit_transform(df.transpose().values)

scaled_df

autoencoder.fit(scaled_df,scaled_df,epochs=15)

encoded_2dim = encoder.predict(scaled_df)

encoded_2dim

df.transpose().index

res = pd.DataFrame(data=encoded_2dim,
                   index=df.transpose().index,
                   columns=['C1','C2'])

res=res.reset_index()

sns.scatterplot(x='C1',y='C2',data=res,hue='index')

